# Generated by Django 5.2.4 on 2025-08-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=50)),
                ('mounts', models.IntegerField()),
                ('kitten_breed', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='cats/')),
            ],
        ),
        migrations.CreateModel(
            name='KittenOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition_app.cat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition_app.kittenowner')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='kitten_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition_app.kittenowner'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition_app.kittenowner')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition_app.cat')),
            ],
            options={
                'unique_together': {('cat', 'author')},
            },
        ),
    ]
