# Generated by Django 5.2.4 on 2025-08-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('c_cpp', 'C/C++'), ('python', 'Python'), ('database', 'Database'), ('telegram', 'Telegram Bots')], max_length=20)),
                ('github_url', models.URLField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('years_experience', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
