# Generated by Django 5.2.4 on 2025-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('c_cpp', 'C/C++'), ('python', 'Python'), ('database', 'Database'), ('devops', 'DevOps')], max_length=20),
        ),
    ]
