# Generated by Django 5.2.4 on 2025-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('c_cpp', 'C/C++'), ('python', 'Python'), ('database', 'Database'), ('devops', 'DevOps'), ('tg bots', 'tg bots')], max_length=20),
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('c_cpp', 'C/C++'), ('gnu make', 'GNU Make'), ('check', 'Check'), ('ncurses', 'Ncurses'), ('python', 'Python'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('django', 'Django'), ('database', 'Database'), ('mysql', 'MySQL'), ('sqlalchemy', 'SQLAlchemy'), ('postgersql', 'PostgreSQL'), ('django orm', 'Django ORM'), ('devops', 'DevOps'), ('linux', 'Linux')], max_length=30)),
                ('projects', models.ManyToManyField(to='core.project')),
            ],
        ),
    ]
