-- insert into person_order
-- select
--     (select coalesce(max(id), 0)+1
--      from person_order),
--     (select id
--      from person
--      where name = 'Denis'),
--     (select id
--      from menu
--      where pizza_name = 'sicilian pizza'), '2022-02-24'
-- where not exists
--         (select 1
--          from person_order po
--          join menu m on m.id = po.menu_id
--          join pizzeria pz on pz.id = m.pizzeria_id
--          join person p on p.id = po.person_id
--          where p.name = 'Denis'
--              and pz.name = 'Dominos'
--              and po.order_date = '2022-02-24'
--              and m.pizza_name = 'sicilian pizza' );


-- insert into person_order
-- select
--     (select coalesce(max(id), 0)+1
--      from person_order),
--     (select id
--      from person
--      where name = 'Irina'),
--     (select id
--      from menu
--      where pizza_name = 'sicilian pizza'), '2022-02-24'
-- where not exists
--         (select 1
--          from person_order po
--          join menu m on m.id = po.menu_id
--          join pizzeria pz on pz.id = m.pizzeria_id
--          join person p on p.id = po.person_id
--          where p.name = 'Irina'
--              and pz.name = 'Dominos'
--              and po.order_date = '2022-02-24'
--              and m.pizza_name = 'sicilian pizza' );

select * from person_order